service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs14.x
  iam: 
    role:
      statements:
        - Effect: Allow
          Action: 'dynamodb:*'
          Resource: arn:aws:dynamodb:us-east-1:709239819812:table/usersTable

plugins:
  - serverless-dynamodb
  - serverless-offline

package: 
  individually: true
  patterns:
    - "!*/**"

custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      docker: false
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  get-users:
    handler: getusers/handler.getUsers
    package: 
      patterns:
        - "getusers/handler.js"
    events:
      - http:
          path: users/{id}
          method: GET
  create-users:
    handler: createUsers/handler.createUsers
    package: 
      patterns:
        - "createUsers/handler.js"
    events:
      - http:
          path: users
          method: POST          
  update-users:
    handler: updateUsers/handler.updateUsers
    package: 
      patterns:
        - "updateUsers/handler.js"
    events:
      - http:
          path: users/{id}
          method: PATCH  
  delete-users:
    handler: deleteUsers/handler.deleteUsers
    runtime: python3.8
    package: 
      patterns:
        - "deleteUsers/handler.py"
    events:
      - http:
          path: users/{id}
          method: DELETE 

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
          